import type pg from "pg";
import type { PipelineResource, PipelineStageResource } from "./pipelines.js";

export interface PipelineCreateInput { name: string; description?: string | null; icon?: string | null; color?: string | null; is_default?: boolean; is_template?: boolean; template_category?: string | null; order_num?: number; }
export type PipelineUpdateInput = Partial<PipelineCreateInput>;
 export interface PipelineStageCreateInput { name: string; color: string; order_num: number; }
export type PipelineStageUpdateInput = Partial<PipelineStageCreateInput>;
export type PipelineDeleteResult = { ok: true; pipeline: { id: string } } | { ok: false; reason: "pipeline_not_found" | "pipeline_in_use" };
export type StageDeleteResult = { ok: true; stage: { id: string } } | { ok: false; reason: "pipeline_not_found" | "stage_not_found" | "stage_in_use" };
export interface PipelineCrudRepository { createPipeline(companyId: number, userId: number, input: PipelineCreateInput): Promise<PipelineResource>; updatePipeline(companyId: number, pipelineId: number, input: PipelineUpdateInput): Promise<PipelineResource | null>; deletePipeline(companyId: number, pipelineId: number): Promise<PipelineDeleteResult>; createStage(companyId: number, userId: number, pipelineId: number, input: PipelineStageCreateInput): Promise<PipelineStageResource | null>; updateStage(companyId: number, pipelineId: number, stageId: number, input: PipelineStageUpdateInput): Promise<PipelineStageResource | null>; deleteStage(companyId: number, pipelineId: number, stageId: number): Promise<StageDeleteResult>; }
type PipelineRow = { id:number; name:string; description:string|null; icon:string|null; color:string|null; is_default:boolean|null; is_template:boolean|null; template_category:string|null; order_num:number; created_by:number|null; created_at:Date; updated_at:Date };
type StageRow = { id:number; pipeline_id:number; name:string; color:string; order_num:number; created_at:Date; updated_at:Date };
const pipelineColumns = "id,name,description,icon,color,is_default,is_template,template_category,order_num,created_by,created_at,updated_at";
const stageColumns = "id,pipeline_id,name,color,order_num,created_at,updated_at";
const toPipeline=(r:PipelineRow):PipelineResource=>({id:String(r.id),name:r.name,description:r.description,icon:r.icon,color:r.color,is_default:r.is_default??false,is_template:r.is_template??false,template_category:r.template_category,order_num:r.order_num,created_by_user_id:r.created_by===null?null:String(r.created_by),created_at:r.created_at.toISOString(),updated_at:r.updated_at.toISOString()});
const toStage=(r:StageRow):PipelineStageResource=>({id:String(r.id),pipeline_id:String(r.pipeline_id),name:r.name,color:r.color,order_num:r.order_num,created_at:r.created_at.toISOString(),updated_at:r.updated_at.toISOString()});
export class PostgresPipelineCrudRepository implements PipelineCrudRepository {
 constructor(private readonly pool:pg.Pool){}
 private async tx<T>(fn:(c:pg.PoolClient)=>Promise<T>):Promise<T>{const c=await this.pool.connect();try{await c.query("BEGIN");await c.query("SELECT set_config('zinto.integration_api_origin','api',true)");const v=await fn(c);await c.query("COMMIT");return v;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
 private async record(c:pg.PoolClient,companyId:number,userId:number|null,event:string,type:string,id:number,payload:unknown){const j=JSON.stringify(payload);await c.query("INSERT INTO integration_api_audit_records (company_id,actor_user_id,action,resource_type,resource_id,new_values) VALUES ($1,$2,$3,$4,$5,$6::jsonb)",[companyId,userId,event,type,id,j]);await c.query("INSERT INTO integration_api_outbox (company_id,event_type,resource_type,resource_id,payload) VALUES ($1,$2,$3,$4,$5::jsonb)",[companyId,event,type,id,j]);}
 async createPipeline(companyId:number,userId:number,input:PipelineCreateInput){return this.tx(async c=>{const r=await c.query<PipelineRow>(`INSERT INTO pipelines (company_id,name,description,icon,color,is_default,is_template,template_category,order_num,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING ${pipelineColumns}`,[companyId,input.name,input.description??null,input.icon??null,input.color??null,input.is_default??false,input.is_template??false,input.template_category??null,input.order_num??0,userId]);const v=toPipeline(r.rows[0]!);await this.record(c,companyId,userId,"pipeline.created","pipeline",Number(v.id),v);return v;});}
 async updatePipeline(companyId:number,pipelineId:number,input:PipelineUpdateInput){return this.tx(async c=>{const r=await c.query<PipelineRow>(`UPDATE pipelines SET name=CASE WHEN $3 THEN $4 ELSE name END,description=CASE WHEN $5 THEN $6 ELSE description END,icon=CASE WHEN $7 THEN $8 ELSE icon END,color=CASE WHEN $9 THEN $10 ELSE color END,is_default=CASE WHEN $11 THEN $12 ELSE is_default END,is_template=CASE WHEN $13 THEN $14 ELSE is_template END,template_category=CASE WHEN $15 THEN $16 ELSE template_category END,order_num=CASE WHEN $17 THEN $18 ELSE order_num END,updated_at=now() WHERE id=$1 AND company_id=$2 RETURNING ${pipelineColumns}`,[pipelineId,companyId,"name"in input,input.name??null,"description"in input,input.description??null,"icon"in input,input.icon??null,"color"in input,input.color??null,"is_default"in input,input.is_default??false,"is_template"in input,input.is_template??false,"template_category"in input,input.template_category??null,"order_num"in input,input.order_num??0]);const row=r.rows[0];if(!row)return null;const v=toPipeline(row);await this.record(c,companyId,null,"pipeline.updated","pipeline",pipelineId,v);return v;});}
 async deletePipeline(companyId:number,pipelineId:number):Promise<PipelineDeleteResult>{return this.tx(async c=>{const o=await c.query("SELECT id FROM pipelines WHERE id=$1 AND company_id=$2",[pipelineId,companyId]);if(!o.rows[0])return{ok:false,reason:"pipeline_not_found"};const d=await c.query("SELECT 1 FROM deals WHERE pipeline_id=$1 AND company_id=$2 LIMIT 1",[pipelineId,companyId]);if(d.rows[0])return{ok:false,reason:"pipeline_in_use"};await c.query("DELETE FROM pipelines WHERE id=$1 AND company_id=$2",[pipelineId,companyId]);await this.record(c,companyId,null,"pipeline.deleted","pipeline",pipelineId,{id:String(pipelineId)});return{ok:true,pipeline:{id:String(pipelineId)}};});}
 async createStage(companyId:number,userId:number,pipelineId:number,input:PipelineStageCreateInput){return this.tx(async c=>{const o=await c.query("SELECT id FROM pipelines WHERE id=$1 AND company_id=$2",[pipelineId,companyId]);if(!o.rows[0])return null;const r=await c.query<StageRow>(`INSERT INTO pipeline_stages (pipeline_id,company_id,name,color,order_num) VALUES ($1,$2,$3,$4,$5) RETURNING ${stageColumns}`,[pipelineId,companyId,input.name,input.color,input.order_num]);const v=toStage(r.rows[0]!);await this.record(c,companyId,userId,"pipeline_stage.created","pipeline_stage",Number(v.id),v);return v;});}
 async updateStage(companyId:number,pipelineId:number,stageId:number,input:PipelineStageUpdateInput){return this.tx(async c=>{const r=await c.query<StageRow>(`UPDATE pipeline_stages SET name=CASE WHEN $4 THEN $5 ELSE name END,color=CASE WHEN $6 THEN $7 ELSE color END,order_num=CASE WHEN $8 THEN $9 ELSE order_num END,updated_at=now() WHERE id=$1 AND pipeline_id=$2 AND company_id=$3 RETURNING ${stageColumns}`,[stageId,pipelineId,companyId,"name"in input,input.name??null,"color"in input,input.color??null,"order_num"in input,input.order_num??0]);const row=r.rows[0];if(!row)return null;const v=toStage(row);await this.record(c,companyId,null,"pipeline_stage.updated","pipeline_stage",stageId,v);return v;});}
 async deleteStage(companyId:number,pipelineId:number,stageId:number):Promise<StageDeleteResult>{return this.tx(async c=>{const p=await c.query("SELECT id FROM pipelines WHERE id=$1 AND company_id=$2",[pipelineId,companyId]);if(!p.rows[0])return{ok:false,reason:"pipeline_not_found"};const o=await c.query("SELECT id FROM pipeline_stages WHERE id=$1 AND pipeline_id=$2 AND company_id=$3",[stageId,pipelineId,companyId]);if(!o.rows[0])return{ok:false,reason:"stage_not_found"};const d=await c.query("SELECT 1 FROM deals WHERE stage_id=$1 AND company_id=$2 LIMIT 1",[stageId,companyId]);if(d.rows[0])return{ok:false,reason:"stage_in_use"};await c.query("DELETE FROM pipeline_stages WHERE id=$1 AND pipeline_id=$2 AND company_id=$3",[stageId,pipelineId,companyId]);await this.record(c,companyId,null,"pipeline_stage.deleted","pipeline_stage",stageId,{id:String(stageId),pipeline_id:String(pipelineId)});return{ok:true,stage:{id:String(stageId)}};});}
}
